#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'nginx', '2.2.0'
cookbook 'php-fpm', '0.6.2'
cookbook 'wordpress-nginx', :git => 'git://github.com/roots/wordpress-nginx.git'
cookbook 'chef-solo-search'
cookbook 'mysql'
cookbook 'php', '1.2.6'
cookbook 'build-essential'
cookbook 'database'
