#!/usr/bin/env ruby
#^syntax detection

site "https://supermarket.getchef.com/api/v1"

cookbook 'nginx', '2.7.4'
cookbook 'php-fpm', '0.6.10'
cookbook 'wordpress-nginx', :git => 'git://github.com/abarre/wordpress-nginx.git', :ref => '0.3.2'
cookbook 'chef-solo-search'
cookbook 'mysql', '5.3.6'
cookbook 'mysqld', '1.0.2'
cookbook 'php', '1.4.6'
cookbook 'build-essential', '2.0.6'
cookbook 'database', '2.3.1'
cookbook 'newrelic', '2.24.0'
cookbook 'monit', '0.7.1'
cookbook 'timezone', :git => 'https://github.com/jamesotron/cookbooks', :path => 'timezone'
cookbook 'ssmtp'
cookbook 'swap'
cookbook 'varnish', '0.9.18'
cookbook 'backup-manager','0.0.3'
cookbook 'unattended_upgrades', '~> 0.3.0'
