default['wordpress']['database'] = "wordpress"
default['wordpress']['db_username'] = "wordpress"
default['wordpress']['path'] = "/var/www/wordpress"
default['wordpress']['server_name'] = "wordpress"
default['php-fpm']['pool']['www']['listen'] = "/var/run/php-fpm-www.sock"
